# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: OSKAR-PHP-CS-Fixer
      uses: OskarStark/php-cs-fixer-ga@2.16.1.2

    - name: composer-normalize-action
      uses: ergebnis/composer-normalize-action@0.7.0
