name: "Continuous Integration"

on:
  push:
    branches: [ develop ]

jobs:
  composer-normalize:
    name: "composer-normalize"

    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2.0.0"

      - name: composer-normalize-action
        uses: ergebnis/composer-normalize-action@0.7.0
