name: "Continuous Integration"

on:
  push:
    branches: [ develop ]

jobs:
  php-cs-fixer:
    name: PHP-CS-Fixer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: PHP-CS-Fixer
        uses: docker://oskarstark/php-cs-fixer-ga
  composer-normalize:
    name: Composer-Normalize
    runs-on: ubuntu-latest
    steps:
        uses: actions/checkout@v2
      - name: composer-normalize-action
        uses: docker://ergebnis/composer-normalize-action:latest
        env:
          COMPOSER_HOME: /root/.composer
