name: CI

on:
  push:
    branches: [ develop ]

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: PHP-CS-Fixer
        uses: docker://oskarstark/php-cs-fixer-ga
  composer-normalize:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Composer-Normalize
        uses: docker://ergebnis/composer-normalize-action:latest
